### ISSUE TITLE
Should 26 be in the name?

### ISSUE THREAD

**Issue by camio** [beman-project/iterator_interface#9]
If iterator_interface doesn't make the C++26 train, we'll be left in an awkward position with the name of this repository. Should we call it iterator_interface to avoid this issue?

**Comment by steve-downey** [comment]
We should change it now, rather than later. Definitely before anything takes a dependency on it.

**Comment by camio** [comment]
@steve-downey do you want me to go ahead with the rename?

**Comment by tzlaine** [comment]
I'm no longer trying for 26 with iterator_interface.  I'm not sure whether reflection would be a big win for it's implementation/interface, or maybe no help at all.  I can't really investigate that properly with reflection's being such a rapidly moving target.  So, this will come back for 29.

**Comment by camio** [comment]
I renamed the repository to iterator_interface. There's a bunch of files in the repo that need to be changed as a result, but I'd like to do it after my two outstanding PRs get merged to avoid conflicts.
